name: OnPublishedRelease
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
       dotnet restore ./src/L3D.Net/L3D.Net.csproj
       dotnet restore ./src/L3D.Net.Tests/L3D.Net.Tests.csproj
    - name: Build
      run: |
       dotnet build --no-restore --configuration Release ./src/L3D.Net/L3D.Net.csproj
       dotnet build --no-restore --configuration Debug ./src/L3D.Net.Tests/L3D.Net.Tests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/L3D.Net.Tests/L3D.Net.Tests.csproj
    - name: publish on nuget.org
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ./src/L3D.Net/L3D.Net.csproj
        PACKAGE_NAME: L3D.Net
        VERSION_STATIC: 1.0.0
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUGET_SOURCE: https://api.nuget.org
        INCLUDE_SYMBOLS: false
